### ISSUE TITLE
Don't works

### ISSUE THREAD

**Issue by MattixNow** [herrmannplatz/vue-cli-plugin-now#4]
Hey your plugin don't work, the now.json file is note created with the dist/ path

**Comment by herrmannplatz** [comment]
This plugin follows the [now guide](https://zeit.co/guides/deploying-vuejs-to-now) for deploying vue js application.

Doing the following steps works in my case:

```
$ npx @vue/cli create now-test
$ cd now-test
$ vue add now
$ now
```

Whats your project structure?

**Comment by MattixNow** [comment]
I'm sorry i was using nuxt js. Sorry.
